spring:
  redis:
    host: 106.52.3.108
    port: 6379
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://${myip}/pd?characterEncoding=utf-8&useSSL=false
  freemarker:
    template-loader-path: classpath:templates/
    suffix: .ftl



myip: 106.52.3.108
mybatis-plus:
  mapper-locations: classpath:sqlmap/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: zxc.pd.pd.model.*
  typeEnumsPackage: pd.*.enums.*
  global-config:
    # 数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: uuid
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: not_empty
      #驼峰下划线转换
      column-underline: true
      #数据库大写下划线转换
      #capital-mode: true
      #逻辑删除配置
      logic-delete-value: 1
      logic-not-delete-value: 0
      db-type: mysql
    #刷新mapper 调试神器
    refresh: true
  # 原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
